Repository pagopa/pagopa-gpd-upload-function, pull requests merged in 2024-01, with the labels that each got.

#2 feat: Add block upload function [PAGOPA-1362]
  .github/workflows/assignee.yml
  .github/workflows/check_metadata_pr.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/deploy.yml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .github/workflows/sonar_analysis.yml
  .github/workflows/update_code.yml
  .gitignore
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  .identity/04_github_identity.tf
  .identity/99_main.tf
  .identity/99_variables.tf
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  host.json
  local.settings.json.example
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/client/GpdClient.java
  src/main/java/it/gov/pagopa/gpd/upload/entity/Status.java
  src/main/java/it/gov/pagopa/gpd/upload/entity/Upload.java
  src/main/java/it/gov/pagopa/gpd/upload/exception/AppException.java
  src/main/java/it/gov/pagopa/gpd/upload/functions/Info.java
  src/main/java/it/gov/pagopa/gpd/upload/functions/UploadFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/model/AppInfo.java
  src/main/java/it/gov/pagopa/gpd/upload/model/RetryStep.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentOptionMetadataModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentOptionModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentPositionModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentPositionsModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/Stamp.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/TransferMetadataModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/TransferModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/enumeration/DebtPositionStatus.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/enumeration/PaymentOptionStatus.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/enumeration/TransferStatus.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/enumeration/Type.java
  src/main/java/it/gov/pagopa/gpd/upload/repository/StatusRepository.java
  src/main/java/it/gov/pagopa/project/Example.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/gpd/upload/functions/ExampleTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/PaymentPositionsGenerator.java
Labels: enhancement, size/large

#4 Pagopa 1395 insightful error
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/client/GpdClient.java
  src/main/java/it/gov/pagopa/gpd/upload/entity/FailedIUPD.java
  src/main/java/it/gov/pagopa/gpd/upload/entity/Upload.java
  src/main/java/it/gov/pagopa/gpd/upload/functions/UploadFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/model/ResponseGPD.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/ExampleTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/PaymentPositionsGenerator.java
Labels: enhancement, size/small

#5 Adding junit tests
  src/test/java/it/gov/pagopa/gpd/upload/functions/InfoTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/UploadFunctionTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/PaymentPositionsGenerator.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/TestUtil.java
  src/test/resources/META-INF/maven/it.gov.pagopa.gpd.upload/gpd-upload-function/pom.properties
Labels: enhancement

#3 feat: Add output result and validation step [PAGOPA-1362]
  .gitignore
  CODEOWNERS
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  local.settings.json
  local.settings.json.example
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/Info.java
  src/main/java/it/gov/pagopa/gpd/upload/UploadFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/functions/UploadFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentOptionMetadataModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentOptionModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentPositionModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentPositionsModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/Stamp.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/TransferMetadataModel.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/TransferModel.java
  src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/InfoTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/UploadFunctionTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/TestUtil.java
Labels: enhancement, size/large

#6 [PAGOPA-1449] chore: GitHub Federated Identity
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/integration_test.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  .identity/04_github_identity.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
Labels: enhancement

#7 feat: Data-layer improvements and responses aggregation [PAGOPA-1446]
  README.md
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/UploadFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/client/GPDClient.java
  src/main/java/it/gov/pagopa/gpd/upload/entity/ResponseEntry.java
  src/main/java/it/gov/pagopa/gpd/upload/entity/Status.java
  src/main/java/it/gov/pagopa/gpd/upload/entity/Upload.java
  src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/PaymentPositionsGenerator.java
Labels: enhancement

#8 feat: report fine-grained response [PAGOPA-1446]
  .identity/99_variables.tf
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/terraform.tfvars
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/UploadFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/client/GPDClient.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/PaymentPositionsGenerator.java
Labels: enhancement, size/small

#10 feat: EventGridSchema handler [PAGOPA-1482]
  .gitignore
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  infra/.terraform.lock.hcl
  infra/04_apim_api.tf
  infra/99_locals.tf
  infra/99_main.tf
  infra/99_variables.tf
  infra/env/weu-dev/backend.ini
  infra/env/weu-dev/backend.tfvars
  infra/env/weu-dev/terraform.tfvars
  infra/env/weu-prod/backend.ini
  infra/env/weu-prod/backend.tfvars
  infra/env/weu-prod/terraform.tfvars
  infra/env/weu-uat/backend.ini
  infra/env/weu-uat/backend.tfvars
  infra/env/weu-uat/terraform.tfvars
  infra/openapi/openapi.json
  infra/policy/_base_policy.xml
  infra/terraform.sh
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/BlobEventFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/UploadFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/client/GPDClient.java
  src/main/java/it/gov/pagopa/gpd/upload/entity/Status.java
  src/main/java/it/gov/pagopa/gpd/upload/model/UploadReport.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentOption.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentOptionMetadata.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentPosition.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentPositions.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/Transfer.java
  src/main/java/it/gov/pagopa/gpd/upload/model/pd/TransferMetadata.java
  src/main/java/it/gov/pagopa/gpd/upload/repository/BlobStorageRepository.java
  src/main/java/it/gov/pagopa/gpd/upload/service/BlockService.java
  src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
  src/main/java/it/gov/pagopa/gpd/upload/util/MapUtils.java
  src/main/java/it/gov/pagopa/gpd/upload/util/PaymentPositionValidator.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/UploadFunctionTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/PaymentPositionsGenerator.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/TestUtil.java
Labels: enhancement, size/large
