Repository pagopa/pagopa-gpd-upload-function, pull requests merged in 2024-02, with the labels that each got.

#12 chore: Fix identity
  .identity/env/prod/backend.tfvars
  .identity/env/uat/backend.tfvars
Labels: size/small

#11 feat: Add decoupling via queue and retry logic [PAGOPA-1410]
  .github/workflows/code_review.yml
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  infra/04_apim_api.tf
  infra/openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/BlobEventFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/ServiceFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/ValidationFunction.java
  src/main/java/it/gov/pagopa/gpd/upload/client/GPDClient.java
  src/main/java/it/gov/pagopa/gpd/upload/entity/PaymentPositionsMessage.java
  src/main/java/it/gov/pagopa/gpd/upload/entity/Upload.java
  src/main/java/it/gov/pagopa/gpd/upload/model/ResponseGPD.java
  src/main/java/it/gov/pagopa/gpd/upload/repository/BlobRepository.java
  src/main/java/it/gov/pagopa/gpd/upload/repository/StatusRepository.java
  src/main/java/it/gov/pagopa/gpd/upload/service/BlockService.java
  src/main/java/it/gov/pagopa/gpd/upload/service/QueueService.java
  src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
  src/main/java/it/gov/pagopa/gpd/upload/util/PaymentPositionValidator.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/gpd/upload/functions/function/InfoTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/function/ServiceFunctionTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/function/ValidationFunctionTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/service/StatusServiceTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/MapUtilsTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/PaymentPositionValidatorTest.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/util/TestUtil.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/utils/PaymentPositionsGenerator.java
  src/test/java/it/gov/pagopa/gpd/upload/functions/utils/TestUtil.java
Labels: enhancement, size/large

#13 feat: add query param toPublish [PAGOPA-1490]
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/gpd/upload/client/GPDClient.java
Labels: enhancement, size/small
